model:
  in_channels: 1
  out_channels: 1
  hidden_dims: [32, 64, 128, 256, 512]
  latent_dim: 8

discriminator:
  in_channels: 1
  hidden_dims: [32, 64, 128, 256, 512]

training:
  learning_rate: 1e-4
  discriminator_lr: 1e-4
  weight_decay: 1e-6
  batch_size: 8
  max_epochs: 200
  num_workers: 4
  
  # Loss weights
  recon_loss_weight: 1.0
  kl_loss_weight: 0.1
  perceptual_loss_weight: 0.1
  disc_loss_weight: 0.5
  gen_loss_weight: 0.1
  
  # Enable adversarial training
  use_discriminator: true

data:
  sample_rate: 16000
  duration: 10.0
  metadata_path: "data/dataset/metadata/train.csv"
  audio_dir: "data/dataset/audio/"
  val_metadata_path: "data/dataset/metadata/val.csv"
  val_audio_dir: "data/dataset/audio/"

logging:
  log_dir: "logs/vae/"
  save_top_k: 3
  monitor: "val/total_loss"